### ISSUE TITLE
refactor: footer, dday 컴포넌트 반응형 반영

### ISSUE THREAD

**Issue by intersoom** [ssu-student-union/homepage-frontend#18]
# 📍 ISSUE : #18

## AS-IS

- 현재 두 컴포넌트 모두 반응형이 적용되어 있지 않음
- DDAY 컴포넌트 carousel 적용되어 있지 않음

## TO-BE

- 1920-1440
- 1440-1080
- 1080-720
- 720-390

4가지 분기 각각에 맞추어 반응형 적용 (피그마 참고)
<img width="763" alt="스크린샷 2024-07-17 오후 4 51 20" src="https://github.com/user-attachments/assets/7e0d6a9e-e781-4f30-94a6-5420c182f3e5">
<img width="803" alt="스크린샷 2024-07-17 오후 4 51 15" src="https://github.com/user-attachments/assets/1c49c534-3405-48cc-9fbf-4f906437ed39">

## TO-DO
- [ ] dday 컴포넌트 반응형 적용
- [ ] dday 컴포넌트 carousel 적용
- [ ] footer 컴포넌트 반응형 적용
