### ISSUE TITLE
chore: packageManager(corepack) 옵션 추가

### ISSUE THREAD

**Issue by EATSTEAK** [ssu-student-union/homepage-frontend#186]
# 📍 ISSUE

## AS-IS

현재 프로젝트는 yarn v1(classic)과 npm을 패키지 매니저로 동시에 사용하고 있습니다(`yarn.lock`과 `package-lock.json`이 동시에 존재 -> 프로젝트 최초 설정 때에는 yarn v1이긴 하네요). 같은 프로젝트에 대해 다른 패키지 매니저를 사용하게 되면, 버전 차이나 패키지 매니저 별 dependency resolver의 동작이 달라 예상치 못한 문제가 발견될 수 있습니다.

또한 신규 팀원이나 개발 인원의 교체가 있을 때마다 관련 컨벤션을 안내하거나 or 체계 없이 개발하는 일이 발생할 수 있습니다.

그리고 제가 개인적으로 `corepack`을 사용 중인데, `corepack`을 사용 중일 경우 `package.json`에 `packageManger` 필드를 설치할 때마다 추가하게 되어 `package.json`에 changes가 지속적으로 발생하는 문제가 있습니다.
## TO-BE

Node.js 16부터 도입된 [Corepack](https://nodejs.org/api/corepack.html)은 서로 다른 환경에서도 같은 패키지 매니저를 사용할 수 있게끔 노드에서 관리해 주는 도구입니다.

`package.json`에 `packageManager` 필드를 선언하고, 프로젝트 루트에서 `corepack enable`을 입력하면 `packageManager`에 선언된 버전의 패키지 매니저를 자동으로 설치하고, `packageManager` 필드가 없다면 자동으로 `packageManager` 필드가 생성됩니다.

이렇게 현재 프로젝트에서 사용하는 패키지 매니저를 지정하면 앞으로 큰 혼란 없이 패키지 관리가 가능해지고, `corepack`을 활성화 한 사람은 더 쉽게 프로젝트를 새로운 환경에서 설정할 수 있으며, 비활성화 한 사람도 잘못 패키지 매니저를 설치하는 일이 줄어듭니다.

~~사실 제가 매번 `package.json`을 Rollback하는게 귀찮아서 올리는 이슈가 아닙니다~~

## TO-DO

- [ ] 프로젝트에서 사용하는 패키지 매니저 정하기
- [ ] lockfile을 하나로 통합(`yarn.lock` or `package-lock.json` or `pnpm-lock.yaml`..?)
- [ ] `packageManager` 필드를 `package.json`에 추가

**Comment by dvp-tae** [comment]
전혀 고려하지 못하고 있던 부분이네요.. 지적 너무 감사드립니다! 금주까지는 회의가 있으니 다같이 이슈 관련해서 이야기 나눠봐요!

**Comment by jongse7** [comment]
와웅... 이렇게 또 하나 알게 되네여... 감사합니다. 태현님 말씀대로 회의 안건으로 하면 좋을거 같아요.
