### ISSUE TITLE
feat: 인권신고게시판 글 목록 뷰

### ISSUE THREAD

**Issue by EATSTEAK** [ssu-student-union/homepage-frontend#189]
# 📍 ISSUE

## 이슈 설명

[WBS](https://www.notion.so/ssu-it/10f4a8d2ea6c80449381dac7ca61d0f8?pvs=4)
[Figma](https://www.figma.com/design/bvPbGZ4yQbtxoW66PCnAuF/%EC%88%AD%EC%8B%A4%EB%8C%80%ED%95%99%EA%B5%90-%EC%B4%9D%ED%95%99%EC%83%9D%ED%9A%8C-%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80?node-id=5914-14759&t=jEhflW6gc3WRbDBb-4)

인권신고 게시판의 글 목록 뷰를 mock data와 함께 구성합니다.

## TO-DO

- [ ] 카테고리 구성
- [ ] 글 상태 속성 표시
- [ ] 권한별 글쓰기 버튼 표시 조정
- [ ] 권한별 글 목록 표시 조정
