### ISSUE TITLE
feat: 건의게시판  UI

### ISSUE THREAD

**Issue by nebulaBdj** [ssu-student-union/homepage-frontend#219]
# 📍 ISSUE :

## 이슈 설명

건의게시판의 GUI 개발
mock data를 이용해 구현

## TO-DO

건의게시판 글목록 뷰
- [x] 총학/자치기구 필터링 버튼
- [x] 상태 필터링 버튼
- [x] 검색
- [x] 페이지네이션

건의게시판 글보기 뷰
- [ ] 건의글
- [ ] 파일
- [ ] 댓글 기능 구현 

건의게시판 글작성 뷰
- [ ] 현재 페이지 구분
- [ ] 해시태그 구현
- [ ] 제목과 건의 날짜 표시
- [ ] 내용 표시
- [ ] 내용에 대한 편집 버튼 (권한별 구현)
- [ ] 댓글 구현
