### ISSUE TITLE
feat: main 페이지 제작

### ISSUE THREAD

**Issue by intersoom** [ssu-student-union/homepage-frontend#22]
# 📍 ISSUE : #22

## 이슈 설명
메인 페이지 UI를 제작합니다.

## TO-DO
- [ ] naver 지도 도입
- [ ] 메인 페이지 기본 ui
- [ ] 반응형 작업
- [ ] api 연결 (추후 따로 이슈 팔게요)
