### ISSUE TITLE
feat: Search, boardHead 컴포넌트 수정

### ISSUE THREAD

**Issue by dvp-tae** [ssu-student-union/homepage-frontend#26]
# 📍 ISSUE : #24

## 이슈 설명
Search 컴포넌트 반응형 수정 중 input 컴포넌트 min-height 속성과 tailwind.config screens 객체 수정 필요
BoardHead subtitle string이 아닌 React.ReactNode로 변경 필요

## TO-DO
- [ ] input.tsx min-heigth 변경
- [ ] tailwind.config.js screens 객체 xs (390px 이하 ) 추가 및 sm (390~720px) 수정
- [ ] Search.tsx 반응형 수정
- [ ] BoardHead subtitle 타입 변경
