### ISSUE TITLE
fix: 컴포넌트 반응형 수정

### ISSUE THREAD

**Issue by dvp-tae** [ssu-student-union/homepage-frontend#28]
# 📍 ISSUE : #28

## 이슈 설명
페이지 작업에 필요한 컴포넌트들의 반응형 수정

## TO-DO
- [ ] category 컴포넌트 반응형 수정
- [ ] boardactionbutton ...props 속성 추가
- [ ] search 컴포넌트 반응형 재조정
- [ ] header 컴포넌트 z-index 속성 추가
