### ISSUE TITLE
Tracking Issue: 인권신고게시판

### ISSUE THREAD

**Issue by EATSTEAK** [ssu-student-union/homepage-frontend#338]
# 📍 ISSUE

## 에러 설명

인권신고게시판 배포 전 버그를 확인하는 Tracking Issue입니다.

- [x] 2024/11/26 백엔드 스키마 변경으로 인한 요청 오류
  - #339
- [x] 백엔드 수정 기능 오류 대응 후 테스트
  - #340 #341
- [x] 수정 창에서 포커스가 최상단에 가있지 않는 문제
  - #346
- [x] `OFFICIAL` 타입의 댓글이 제대로 핸들링되지 않는 문제
  - #347 #348 #349 
- [x] 5MB 이상 파일 첨부 시 업로드 예외 처리
  - #353
- [x] 피침해자 목록과 침해자 목록의 마진이 다른 문제
  - #350 
- [x] 캐시가 존재하는 상태에서 계정 정보 변경 시 업데이트가 되지 않음
  - #352 
- [x] 편집 화면 모바일 레이아웃 개선
  - #356 
- [x] 파일 첨부 오류시 메시지 가시성 개선
  - #358

**Comment by EATSTEAK** [comment]
#340 머지 이후에도 수정 기능 오류 발생, 백엔드 조치 후 재확인 예정

**Comment by EATSTEAK** [comment]
#342 머지 이후 수정 기능 정상 작동

이 이슈는 Tracking-issue로 인권신고게시판 배포시까지 유지될 예정입니다. cc. @jongse7
