### ISSUE TITLE
fix: 청원게시판 categoryName 필드명 변경사항 적용

### ISSUE THREAD

**Issue by dvp-tae** [ssu-student-union/homepage-frontend#361]
# 📍 ISSUE : #361

## 이슈 설명

기존 청원게시판 단 건 조회 api 중 categoryName 필드명에서 category 로 변경 됨에 따른 수정 사항 적용

## TO-DO

- [ ] PostDetailResDto 타입 수정
- [ ] 청원게시판 단 건 조회 변수명 수정
- [ ] 이외 PostDetailResDto 사용 중이던 부분 수정
