### ISSUE TITLE
feat: 제휴 안내 페이지 제작

### ISSUE THREAD

**Issue by intersoom** [ssu-student-union/homepage-frontend#42]
# 📍 ISSUE : 제휴 안내 페이지 제작

## 이슈 설명
제휴 안내 페이지를 제작합니다.
- 메인 페이지
- 등록 페이지
- 상세 페이지

## TO-DO

- [ ] 제휴 안내 메인 페이지
- [ ] 제휴 안내 등록 페이지
- [ ] 제휴 안내 상세 페이지
